plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.txngnx_ttcs_n56'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.example.txngnx_ttcs_n56"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    // Thư viện tạo mã QR (ZXing)
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    // Thư viện kết nối API (Retrofit) để sau này gọi lên Server Node.js/Java
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    // Thư viện giao diện Material Design (để làm các Popup đẹp hơn)
    implementation 'com.google.android.material:material:1.9.0'
}